# Generated by Django 5.1.1 on 2024-09-18 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('absence_date', models.DateTimeField()),
                ('absence_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('reference', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_de_creation', models.DateField(auto_now_add=True)),
                ('picture', models.URLField()),
                ('telephone', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('F', 'WOMEN'), ('M', 'MEN'), ('O', 'OTHER')], max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('matricule', models.CharField(max_length=50)),
                ('classe', models.CharField(choices=[('terminale', 'terminale'), ('premiere', 'premiere'), ('seconde', 'seconde'), ('troisieme', 'troisieme'), ('quatrieme', 'quatrieme'), ('cinquieme', 'cinquieme')], max_length=50)),
                ('parent_number', models.CharField(max_length=50)),
                ('adress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.addressmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
